/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StoreRouteImport } from './routes/store'
import { Route as NebulaNebulaIdRouteImport } from './routes/nebula.$nebulaId'
import { Route as PlayLevelIdRouteImport } from './routes/play.$levelId'
import { Route as SystemSystemIdRouteImport } from './routes/system.$systemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const NebulaNebulaIdRoute = NebulaNebulaIdRouteImport.update({
  id: '/nebula/$nebulaId',
  path: '/nebula/$nebulaId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelIdRoute = PlayLevelIdRouteImport.update({
  id: '/play/$levelId',
  path: '/play/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSystemIdRoute = SystemSystemIdRouteImport.update({
  id: '/system/$systemId',
  path: '/system/$systemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/nebula/$nebulaId': typeof NebulaNebulaIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/system/$systemId': typeof SystemSystemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/nebula/$nebulaId': typeof NebulaNebulaIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/system/$systemId': typeof SystemSystemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/nebula/$nebulaId': typeof NebulaNebulaIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/system/$systemId': typeof SystemSystemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/profile'
    | '/store'
    | '/nebula/$nebulaId'
    | '/play/$levelId'
    | '/system/$systemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/profile'
    | '/store'
    | '/nebula/$nebulaId'
    | '/play/$levelId'
    | '/system/$systemId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/profile'
    | '/store'
    | '/nebula/$nebulaId'
    | '/play/$levelId'
    | '/system/$systemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  StoreRoute: typeof StoreRoute
  NebulaNebulaIdRoute: typeof NebulaNebulaIdRoute
  PlayLevelIdRoute: typeof PlayLevelIdRoute
  SystemSystemIdRoute: typeof SystemSystemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nebula/$nebulaId': {
      id: '/nebula/$nebulaId'
      path: '/nebula/$nebulaId'
      fullPath: '/nebula/$nebulaId'
      preLoaderRoute: typeof NebulaNebulaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$levelId': {
      id: '/play/$levelId'
      path: '/play/$levelId'
      fullPath: '/play/$levelId'
      preLoaderRoute: typeof PlayLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/$systemId': {
      id: '/system/$systemId'
      path: '/system/$systemId'
      fullPath: '/system/$systemId'
      preLoaderRoute: typeof SystemSystemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  StoreRoute: StoreRoute,
  NebulaNebulaIdRoute: NebulaNebulaIdRoute,
  PlayLevelIdRoute: PlayLevelIdRoute,
  SystemSystemIdRoute: SystemSystemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
