/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LuckyDrawRouteImport } from './routes/lucky-draw'
import { Route as MagicRouteImport } from './routes/magic'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StoreRouteImport } from './routes/store'
import { Route as ZenRouteImport } from './routes/zen'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as ChallengesNebulaIdRouteImport } from './routes/challenges.$nebulaId'
import { Route as NebulaNebulaIdRouteImport } from './routes/nebula.$nebulaId'
import { Route as PlayLevelIdRouteImport } from './routes/play.$levelId'
import { Route as SystemSystemIdRouteImport } from './routes/system.$systemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LuckyDrawRoute = LuckyDrawRouteImport.update({
  id: '/lucky-draw',
  path: '/lucky-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicRoute = MagicRouteImport.update({
  id: '/magic',
  path: '/magic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const ZenRoute = ZenRouteImport.update({
  id: '/zen',
  path: '/zen',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChallengesRoute,
} as any)
const ChallengesNebulaIdRoute = ChallengesNebulaIdRouteImport.update({
  id: '/$nebulaId',
  path: '/$nebulaId',
  getParentRoute: () => ChallengesRoute,
} as any)
const NebulaNebulaIdRoute = NebulaNebulaIdRouteImport.update({
  id: '/nebula/$nebulaId',
  path: '/nebula/$nebulaId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelIdRoute = PlayLevelIdRouteImport.update({
  id: '/play/$levelId',
  path: '/play/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemSystemIdRoute = SystemSystemIdRouteImport.update({
  id: '/system/$systemId',
  path: '/system/$systemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/magic': typeof MagicRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/zen': typeof ZenRoute
  '/challenges/$nebulaId': typeof ChallengesNebulaIdRoute
  '/nebula/$nebulaId': typeof NebulaNebulaIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/system/$systemId': typeof SystemSystemIdRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/magic': typeof MagicRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/zen': typeof ZenRoute
  '/challenges/$nebulaId': typeof ChallengesNebulaIdRoute
  '/nebula/$nebulaId': typeof NebulaNebulaIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/system/$systemId': typeof SystemSystemIdRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lucky-draw': typeof LuckyDrawRoute
  '/magic': typeof MagicRoute
  '/profile': typeof ProfileRoute
  '/store': typeof StoreRoute
  '/zen': typeof ZenRoute
  '/challenges/$nebulaId': typeof ChallengesNebulaIdRoute
  '/nebula/$nebulaId': typeof NebulaNebulaIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/system/$systemId': typeof SystemSystemIdRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/challenges'
    | '/friends'
    | '/leaderboard'
    | '/lucky-draw'
    | '/magic'
    | '/profile'
    | '/store'
    | '/zen'
    | '/challenges/$nebulaId'
    | '/nebula/$nebulaId'
    | '/play/$levelId'
    | '/system/$systemId'
    | '/challenges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/friends'
    | '/leaderboard'
    | '/lucky-draw'
    | '/magic'
    | '/profile'
    | '/store'
    | '/zen'
    | '/challenges/$nebulaId'
    | '/nebula/$nebulaId'
    | '/play/$levelId'
    | '/system/$systemId'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/challenges'
    | '/friends'
    | '/leaderboard'
    | '/lucky-draw'
    | '/magic'
    | '/profile'
    | '/store'
    | '/zen'
    | '/challenges/$nebulaId'
    | '/nebula/$nebulaId'
    | '/play/$levelId'
    | '/system/$systemId'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRouteWithChildren
  FriendsRoute: typeof FriendsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LuckyDrawRoute: typeof LuckyDrawRoute
  MagicRoute: typeof MagicRoute
  ProfileRoute: typeof ProfileRoute
  StoreRoute: typeof StoreRoute
  ZenRoute: typeof ZenRoute
  NebulaNebulaIdRoute: typeof NebulaNebulaIdRoute
  PlayLevelIdRoute: typeof PlayLevelIdRoute
  SystemSystemIdRoute: typeof SystemSystemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lucky-draw': {
      id: '/lucky-draw'
      path: '/lucky-draw'
      fullPath: '/lucky-draw'
      preLoaderRoute: typeof LuckyDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic': {
      id: '/magic'
      path: '/magic'
      fullPath: '/magic'
      preLoaderRoute: typeof MagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zen': {
      id: '/zen'
      path: '/zen'
      fullPath: '/zen'
      preLoaderRoute: typeof ZenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/challenges/$nebulaId': {
      id: '/challenges/$nebulaId'
      path: '/$nebulaId'
      fullPath: '/challenges/$nebulaId'
      preLoaderRoute: typeof ChallengesNebulaIdRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/nebula/$nebulaId': {
      id: '/nebula/$nebulaId'
      path: '/nebula/$nebulaId'
      fullPath: '/nebula/$nebulaId'
      preLoaderRoute: typeof NebulaNebulaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$levelId': {
      id: '/play/$levelId'
      path: '/play/$levelId'
      fullPath: '/play/$levelId'
      preLoaderRoute: typeof PlayLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/$systemId': {
      id: '/system/$systemId'
      path: '/system/$systemId'
      fullPath: '/system/$systemId'
      preLoaderRoute: typeof SystemSystemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChallengesRouteChildren {
  ChallengesNebulaIdRoute: typeof ChallengesNebulaIdRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

const ChallengesRouteChildren: ChallengesRouteChildren = {
  ChallengesNebulaIdRoute: ChallengesNebulaIdRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}

const ChallengesRouteWithChildren = ChallengesRoute._addFileChildren(
  ChallengesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRouteWithChildren,
  FriendsRoute: FriendsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LuckyDrawRoute: LuckyDrawRoute,
  MagicRoute: MagicRoute,
  ProfileRoute: ProfileRoute,
  StoreRoute: StoreRoute,
  ZenRoute: ZenRoute,
  NebulaNebulaIdRoute: NebulaNebulaIdRoute,
  PlayLevelIdRoute: PlayLevelIdRoute,
  SystemSystemIdRoute: SystemSystemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
